In [1]:
from IPython.display import Image
Image("img/picture.png")
from IPython.core.display import HTML 
import numpy as np
import pandas as pd
import missingno as msno
import seaborn as sns
import matplotlib.pyplot as plt

# Introducción

## ¿Qué es el procesamiento de Datos?

El EDA y procesamiento de datos consiste en una de las tareas más fundamentales dentro de las labores de un data scientist, dado que un buen procesamiento y exploración, generalmente se puede traducir a un buen input para un futuro modelo. Dentro de las tareas que uno tiene al hacer procesamiento de datos destacamos las siguientes:


   - Feature engineering
   - Feature scaling 
   - Detección de outliers
   - Manejo de valores faltantes
   - Codificación de variables categóricas
   - Discretización de los datos

Dentro de las librerías que sirven para hacer el procesamiento de datos y exploración tenemos las siguientes:

 - `NumPy:` Modulo que permite el manejo de arreglos matriciales y operaciones matemáticas 
 - `Pandas:` Modulo que sirve para el manejo de dataframes
 - `Scikit Learn:` Modulo que nos ayuda con modelos de machine learning y la preparación de datos para los mismos
 - `MatPlotLib y Seaborn:` Modulos para realizar gráficas de los datos

In [2]:
salud = pd.read_csv("Data/ESalud19.csv")

In [3]:
salud.head(20) #NaN = Not a Number

,SEXO,EDAD,N_EDU,E_CIVIL,PESO,ESTATURA,CINTURA,PANTORRILLA,IMC,CANSANCIO,...,PAS1,PAD1,PRES1,PAS2,PAD2,PRES2,PAS3,PAD3,PRES3,FEXP
0,MUJER,38,13 o más años,CONVIVIENTE O PAREJA SIN ACUERDO DE UNIÓN CIVIL,NaN,NaN,NaN,NaN,NaN,SÍ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,MUJER,25,13 o más años,SOLTERO(A),57.4,157.3,73.2,NaN,23.198208,SÍ,...,94.0,62.0,84.0,96.0,58.0,82.0,91.0,60.0,76.0,NaN
2,MUJER,20,13 o más años,SOLTERO(A),71.6,165.3,81.1,NaN,26.203983,SÍ,...,97.0,66.0,79.0,104.0,64.0,69.0,100.0,68.0,81.0,NaN
3,MUJER,85,13 o más años,VIUDO(A),60.3,159.4,108.1,33.6,23.732346,NaN,...,225.0,79.0,59.0,210.0,88.0,60.0,215.0,89.0,60.0,NaN
4,HOMBRE,41,13 o más años,SOLTERO(A),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,MUJER,30,13 o más años,SOLTERO(A),66.3,162.8,75.8,NaN,25.015243,NaN,...,107.0,64.0,67.0,110.0,57.0,74.0,103.0,70.0,77.0,NaN
6,MUJER,53,13 o más años,CASADO (A),80.1,157.5,101.6,NaN,32.290249,NaN,...,100.0,61.0,63.0,102.0,65.0,64.0,103.0,76.0,67.0,325.515411
7,MUJER,75,13 o más años,CASADO (A),72.9,153.5,96.0,35.2,30.939320,NaN,...,133.0,69.0,68.0,130.0,66.0,70.0,132.0,62.0,68.0,NaN
8,HOMBRE,34,13 o más años,CASADO (A),63.5,164.3,79.2,NaN,23.523319,NaN,...,109.0,69.0,55.0,118.0,73.0,53.0,116.0,66.0,49.0,948.649292
9,HOMBRE,25,13 o más años,CONVIVIENTE O PAREJA SIN ACUERDO DE UNIÓN CIVIL,60.4,181.4,74.1,NaN,18.355337,SÍ,...,112.0,70.0,82.0,116.0,67.0,73.0,111.0,73.0,78.0,NaN
10,MUJER,37,13 o más años,SOLTERO(A),70.8,164.7,87.4,NaN,26.100334,NaN,...,101.0,65.0,75.0,98.0,62.0,81.0,101.0,64.0,78.0,NaN
11,MUJER,51,13 o más años,CASADO (A),56.9,159.1,76.2,NaN,22.478737,NaN,...,115.0,78.0,72.0,112.0,81.0,75.0,113.0,72.0,71.0,165.972366
12,HOMBRE,37,13 o más años,SOLTERO(A),99.4,166.5,107.4,NaN,35.855675,NaN,...,144.0,99.0,76.0,147.0,110.0,78.0,140.0,99.0,76.0,NaN
13,HOMBRE,34,13 o más años,CASADO (A),63.9,158.5,85.1,NaN,25.435620,NaN,...,121.0,73.0,54.0,109.0,67.0,53.0,114.0,66.0,57.0,1004.143005
14,MUJER,39,13 o más años,SOLTERO(A),68.0,159.0,83.2,NaN,26.897670,NaN,...,109.0,67.0,86.0,107.0,70.0,86.0,107.0,69.0,83.0,NaN
15,HOMBRE,27,13 o más años,SOLTERO(A),69.0,160.9,83.0,NaN,26.652442,NaN,...,94.0,59.0,72.0,94.0,59.0,75.0,93.0,62.0,72.0,10134.053711
16,MUJER,35,13 o más años,CASADO (A),81.6,158.8,91.7,NaN,32.358558,NaN,...,122.0,84.0,73.0,121.0,84.0,74.0,124.0,87.0,77.0,NaN
17,MUJER,31,13 o más años,SOLTERO(A),87.7,154.0,102.3,NaN,36.979255,NaN,...,106.0,62.0,51.0,102.0,67.0,51.0,108.0,67.0,50.0,NaN
18,HOMBRE,34,13 o más años,CASADO (A),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,MUJER,31,13 o más años,SOLTERO(A),113.7,166.0,104.0,NaN,41.261431,SÍ,...,126.0,87.0,67.0,115.0,80.0,70.0,119.0,81.0,69.0,NaN

In [4]:
salud.shape

(6233, 33)

In [5]:
salud.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6233 entries, 0 to 6232
Data columns (total 33 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   SEXO            6233 non-null   object
 1   EDAD            6233 non-null   int64
 2   N_EDU           6174 non-null   object
 3   E_CIVIL         6213 non-null   object
 4   PESO            5488 non-null   float64
 5   ESTATURA        5495 non-null   float64
 6   CINTURA         5479 non-null   float64
 7   PANTORRILLA     1727 non-null   float64
 8   IMC             5483 non-null   float64
 9   CANSANCIO       955 non-null    object
 10  RESPIRA         6233 non-null   object
 11  DEPORTE         6233 non-null   object
 12  FUMA            6233 non-null   object
 13  FUMA_ACTUAL     6233 non-null   object
 14  FRUTA           6233 non-null   int64
 15  SINT_DEPRESION  5786 non-null   object
 16  DIABETES        6233 non-null   object
 17  HTA             5643 non-null   object
 18  SODIO_ORINA     3691 non-null   float64
 19  GLUCOSA         5117 non-null   float64
 20  HDL             3715 non-null   float64
 21  LDL             3690 non-null   float64
 22  COLESTEROL      3715 non-null   float64
 23  PAS1            5516 non-null   float64
 24  PAD1            5516 non-null   float64
 25  PRES1           5516 non-null   float64
 26  PAS2            5516 non-null   float64
 27  PAD2            5516 non-null   float64
 28  PRES2           5516 non-null   float64
 29  PAS3            5516 non-null   float64
 30  PAD3            5516 non-null   float64
 31  PRES3           5516 non-null   float64
 32  FEXP            1376 non-null   float64
dtypes: float64(20), int64(2), object(11)
memory usage: 1.6+ MB

# Entendiendo los tipos de datos

## ¿Qué es una variable?

Una variable es una característica o atributo en una cierta muestra de una población. Por ejemplo, si en nuestra población tenemos personas y extraemos una muestra, posibles variables son:

-  **Nombre**: Jorge, Miguel, Alicia
-  **Edad**  : 35, 12, 56
-  **Género**: Femenino, Masculino
-  **Nacionalidad**: Argentina, Italiana, Chilena
-  **Año de Nacimiento** : 10-10-1990, 12-03-1983

Nos fijamos que existen distintos tipos de variables en este ejemplo, algunos son fechas, algunos son categorías, algunas numéricas, etc. En este sentido, diremos que las variables se pueden clasificar en los siguientes tipos:

1. Dato Numérica
    - Discreta
    -  Continua
2. Dato Categórico
    - Ordinal
    - Nominal
3. Variable de Fecha y Tiempo
4. Variable Mixtas

#### Ejemplos

In [6]:
titanic_data = sns.load_dataset('titanic') # importa desde el repositorio online

In [7]:
type(titanic_data)

pandas.core.frame.DataFrame

In [8]:
titanic_data.head() #muestra las primeras 5 filas del dataset

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

- survived: Si el pasajero sobrevivió o no (1-Si, 0-No)
- pclass : clase del pasajero (1-primera, 2-segunda, 3-tercera)
- sex : sexo
- sibsp : número de hermanos/esposos abordo 
- parch : número de padres/hijos abordo
- fare : tarifa del ticket
- embarked : puerto de embarque (C-Cherbourg, Q-Queenstown, S-Southampton
- class : clase del pasajero
- who: si es hombre o mujer
- adult_male : si es adulto y hombre
- deck : cubiertas del barco (de la A a la G)
- embark_town : ciudad de embarque, mismas que embarked
- alive : si el pasajero sobrevivió o no
- alone : si viaja solo o no

# Datos Faltantes o Missing Values

Un dato faltante consiste en valores no observados para alguna(s) variable(s), en algún(os) registro(s). Lo anterior es bastante sensible, en particular cuando estamos pensando en generar algún tipo de modelo o estudio, estos valores pueden generar problemas o influencias en nuestros proceso.

Las causas por las cuales se generan estos datos faltantes son variadas, pero las más típicas son:

1. **No ingresadas, ya sea intencionalmente o no:** La persona o maquina encargada de recolectar los datos, omitió algunos de manera intencionada o no (Ej. En un fraude se quiere omitir un registro para eliminar evidencia)
2. **No disponibles:** Si generando registros de individuos, pero dentro de la recolección existen individuos sin ese dato (Ej. Muestras de sangre para revisar colesterol, y tenemos un individuo sin el examen correspondiente)
3. **Errores:** Estos se pueden deber a multiples cosas, tanto errores humanos como de sistemas.

Los efectos como ya se mencionaron, pueden ser los siguientes:

1. **Problemas con los módulos utilizados** (No todos tienen tratamiento de datos faltantes)
2. **Datos distorcionados** (Al faltar registros, podemos no estar considerando parte importante de los datos)
3. **Performance de modelos** (Nuevamente no todos los modelos tienen tratamiento de estos datos)

En Python, los datos faltantes son representados con `NaN`, que significa "Not a Number". También podemos encontrar valores representados por `None`, donde la diferencia es la siguiente

- `None` representa un dato faltante, pero su tipo no es numéricos, esto es, que cualquier columna que contenga un `None` no puede ser de tipo numérico.
- `NaN` signfica "Not a Number", por lo que el registro con `NaN` no es un número en una columna que si es de tipo numérico (`int`, `float`).

In [9]:
ej1 = pd.Series([3,None])
display(ej1)
ej2 = pd.Series(["3",None])
display(ej2)

0    3.0
1    NaN
dtype: float64

0       3
1    None
dtype: object

In [10]:
titanic_data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [11]:
np.nan + 5

nan

In [12]:
np.nan + 5

nan

In [ ]:
None + 5

¿Cómo podemos saber si nuestro dataset tiene o no datos faltantes?

Existen dos funciones o métodos que nos permiten obtener esta información, que son `info()` y `isna()`, las cuales revisaremos con el siguiente ejemplo. Consideremos un dataset que contiene registros de calidad de aire de 3 localidades, por cada hoy en el año 2020. Este dataset contiene las mediciones NO2, Temperatura, Humedad, Velocidad y Dirección del viento.

In [13]:
air_data = pd.read_csv('Data/Airdata.csv') # lectura

display(air_data.head())
display(air_data.tail())

,DateTime,Temperature,Humidity,Wind_Speed,Wind_Direction,NO2_Location_A,NO2_Location_B,NO2_Location_C
0,1/1/2020 0:00,2.180529,87,1.484318,75.963760,39.23,52.88,62.37
1,1/1/2020 1:00,1.490529,89,2.741678,113.198590,38.30,44.95,52.53
2,1/1/2020 2:00,1.690529,85,3.563818,135.000000,NaN,48.40,54.80
3,1/1/2020 3:00,1.430529,84,2.811690,129.805570,37.28,47.18,50.80
4,1/1/2020 4:00,0.840529,86,1.800000,126.869896,29.97,41.48,54.43

,DateTime,Temperature,Humidity,Wind_Speed,Wind_Direction,NO2_Location_A,NO2_Location_B,NO2_Location_C
8779,12/31/2020 19:00,4.920528,72,4.553680,251.56506,53.44,32.65,66.82
8780,12/31/2020 20:00,4.990529,74,3.259939,186.34020,49.80,34.03,67.31
8781,12/31/2020 21:00,4.360529,84,10.587917,252.18112,43.32,25.55,59.33
8782,12/31/2020 22:00,3.820528,88,8.435069,219.80557,39.88,19.90,43.70
8783,12/31/2020 23:00,3.170529,89,6.792466,212.00539,39.04,30.33,46.87

In [14]:
#Utilizamos la función info
air_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   DateTime        8784 non-null   object
 1   Temperature     8784 non-null   float64
 2   Humidity        8784 non-null   int64
 3   Wind_Speed      8784 non-null   float64
 4   Wind_Direction  8784 non-null   float64
 5   NO2_Location_A  8664 non-null   float64
 6   NO2_Location_B  8204 non-null   float64
 7   NO2_Location_C  8652 non-null   float64
dtypes: float64(6), int64(1), object(1)
memory usage: 549.1+ KB

notamos que esta función nos permite obtener que variables tienen o no datos faltantes, pero no indica cuales son. De ahí la importancia también de la función `isna` que veremos a continuación

In [15]:
air_data.isna()

,DateTime,Temperature,Humidity,Wind_Speed,Wind_Direction,NO2_Location_A,NO2_Location_B,NO2_Location_C
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
8779,False,False,False,False,False,False,False,False
8780,False,False,False,False,False,False,False,False
8781,False,False,False,False,False,False,False,False
8782,False,False,False,False,False,False,False,False
8783,False,False,False,False,False,False,False,False

In [16]:
#Recordar que las variables boolean True = 1 y False = 0, por lo que podemos sumar para ver cuántos datos faltantes tenemos
air_data.isna().sum()

DateTime            0
Temperature         0
Humidity            0
Wind_Speed          0
Wind_Direction      0
NO2_Location_A    120
NO2_Location_B    580
NO2_Location_C    132
dtype: int64

In [17]:
air_data.isnull()

,DateTime,Temperature,Humidity,Wind_Speed,Wind_Direction,NO2_Location_A,NO2_Location_B,NO2_Location_C
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
8779,False,False,False,False,False,False,False,False
8780,False,False,False,False,False,False,False,False
8781,False,False,False,False,False,False,False,False
8782,False,False,False,False,False,False,False,False
8783,False,False,False,False,False,False,False,False

In [18]:
air_data.isnull().sum()

DateTime            0
Temperature         0
Humidity            0
Wind_Speed          0
Wind_Direction      0
NO2_Location_A    120
NO2_Location_B    580
NO2_Location_C    132
dtype: int64

In [19]:
#tambien se puede usar isnull de manera indistinta
air_data.isnull().sum().sort_values(ascending = False)

NO2_Location_B    580
NO2_Location_C    132
NO2_Location_A    120
DateTime            0
Temperature         0
Humidity            0
Wind_Speed          0
Wind_Direction      0
dtype: int64

y también lo podemos llevar a porcentaje de NaN por columna

In [20]:
total = air_data.isna().sum().sort_values(ascending = False)
percent = (air_data.isna().sum() / air_data.isna().count()).sort_values(ascending = False)*100

missing_data = pd.concat([total, percent], axis = 1, keys = ['Total', 'Percent'])
missing_data

                Total   Percent
NO2_Location_B    580  6.602914
NO2_Location_C    132  1.502732
NO2_Location_A    120  1.366120
DateTime            0  0.000000
Temperature         0  0.000000
Humidity            0  0.000000
Wind_Speed          0  0.000000
Wind_Direction      0  0.000000

o también...

In [ ]:
air_data.isna().mean().sort_values(ascending=False)*100

También podemos visualizar los datos faltantes, utilizando el módulo `missingno`, que entrega un gráfico bastante ilustrativo de como se distribuyen a lo largo de los registros, los distintos valores faltantes en las distintas variables.

In [ ]:
msno.bar(air_data)

In [ ]:
msno.bar(titanic_data)

In [ ]:
titanic_data.info()

In [ ]:
msno.matrix(air_data,labels=True,figsize=(50,20))

In [ ]:
msno.matrix(titanic_data,labels=True,figsize=(50,20))

Como ya mencionamos antes, existen diversas formas en que se pueden producir datos faltantes, y aquí tenemos algunas de esas formas de manera más ejemplificada:

- Error Humano
- Encuestados no quieren responder ciertas preguntas
- Encuestador no entiende la pregunta
- El valor obtenido es claramente erróneo, por tanto se elimina
- Sin tiempo para responder
- Registros perdidos debido a la falta de una gestión eficaz de la base de datos
- Eliminación intencional y omisión de la recopilación de los datos
- Participante abandona en medio del estudio
- Manipulación de terceros o bloqueo de la recopilación de datos
- Observaciones perdidas
- Bugs en programas
- Malfuncionamiento del sensor

De todas maneras, e independiente de qué causó los datos faltantes, podemos categorizar este tipo de errores en 3 tipos, como sigue:

- **Missing Completely at Random (MCAR):** Estos son valores faltantes completamente al azar, y se refiere a ellos de esta manera a aquellos en los que no hay razón para creer que los valores faltan debido a alguna razón sistemática. Cuando un dato faltante es clasificado en **MCAR**, entonces la falta de ese dato podría haber sido perfectamente cualquier otra.
    - **Ejemplo:** Si un sensor de calidad de aire le falla la comunicación con el servidor para registrar los datos, debido a la caída de conexión de su internet satelital debido al paso de un asteroide muy cerca del satelite.

- **Missing at Random (MAR):** Este tipo ocurre cuando cuando la probabilidad de ser dato faltante en una variable a lo largo de los registros, no es uniforme.
    - **Ejemplo:** Si vientos fuertes causan aveces el malfuncionamiento de un sensor y por ello, este no obtiene registros, entonces será más probable tener datos faltantes en día de viento fuerte que cuando no.
    
    
- **Missing not at Random (MNAR):** Este tipo, y tal como lo dice su nombre, no tiene nada de aleatorio, es decir, sabremos exactamente que observación tendrá un valor faltante.
    - **Ejemplo:** Si tenemos un sensor que ha sido manipulado para que no muestre su datos.

## Tratamiento de Missing Values

Existen distintos enfoques cuando nos enfrentamos a datos faltantes, en el sentido del tratamiento que debe darseles (Porque hay que hacer algo, o vivir con las consecuencias de no hacer nada). En este sentido, tenemos las siguientes opciones:

- Conservar los datos originales
- Eliminar las filas con datos faltantes
- Eliminar las variables con datos faltantes
- Imputar un valor

Si conservamos los datos originales, tal y como vienen, entonces tendremos que siempre tener cuidado con nuestros análisis, así como también con los futuros modelos que podremos utilizar, dado que no todos los modelos tienen tratamiento de datos faltantes.

Ahora para ejemplificar los otros métodos, consideremos el siguiente dataset

In [ ]:
dic_data = {'Name':['Jon','James','Mike','Nick','Harry','Sally','Laura'], 'Age':[25,None,62,42,45,26,35], 'Sex':['Male','Male','Male','Male','Male','Female','Female'], 'BloodGroup':['O+','A+','O+','B-','AB+',None,'B+']}
ej_data = pd.DataFrame(dic_data)
ej_data

In [ ]:
np.mean(ej_data.Age)

In [ ]:
ej_data['Age'].dropna().mean()

Respecto al método de eliminar los registros que contienen datos faltantes, obtendriamos lo siguiente:

In [ ]:
ej_data.dropna(axis = 0)

In [ ]:
ej_data.drop(["Age"], axis = 1, inplace=False)

In [ ]:
ej_data.dropna(axis =1)

In [ ]:
ej_data

Respecto a este método, podemos comentar lo siguiente:

**Ventajas**:
- Extremadamente simple de aplicar.
- Si los missing values son completamente al azar, entonces al eliminarlos la distribución de la variable se conserva.

**Desventajas**:
- Si la cantidad de missing values es alta, una gran cantidad de data será eliminada.
- No aplicable para missing values que no sean completamente aleatorios.

Respecto al segundo método, de eliminar las variables que contienen datos faltantes, tendríamos lo siguiente:

In [ ]:
ej_data.dropna(axis= 1)

In [ ]:
titanic_data.info()

Para hacer esto, se deben tener las siguientes consideraciones:

- Se eliminan aquellas variables que no son claves para el proyecto a realizar.
- Generalmente se opta por este método cuando la cantidad de missing values supera el 25%

### Imputación de missing values

La imputación de datos es una técnica que nos permite no perder registros, cambiando los valores `NaN` por otro (que dependerán de la técnica que se utilice). En este sentido tenemos dos opciones que son relativamente comunes:

- **Imputación por medida de tendencia central** 
- **Imputación por regresión**

Imputación por Media o Mediana o Moda

Ejemplo:

In [ ]:
ej_data

In [ ]:
ej_data.Age.mean() ## La función mean, realiza el dropna de manera interna, por lo que no es necesario volver a hacerlo.

In [ ]:
ej_data.Age.median()

In [ ]:
ej_data.BloodGroup.mode()[0]

In [ ]:
#Imputamos con la media y la moda
ej_data.fillna({'Age':np.round(ej_data.Age.mean(),0), 'BloodGroup':ej_data.BloodGroup.mode()[0]})

In [ ]:
#Imputamos con la mediana y la moda
ej_data.fillna({'Age':np.round(ej_data.Age.median(),0), 'BloodGroup':ej_data.BloodGroup.mode()[0]})

Veamos ahora un ejemplo práctico utilizando el dataset Titanic

In [ ]:
titanic_data.head()

Tomemos sólo algunas columnas con datos numéricos para hacer el ejercicio de imputacion

In [ ]:
titanic_data_sub  = titanic_data[["deck", "pclass", "age", "fare"]]

In [ ]:
titanic_data.head()

In [ ]:
titanic_data.shape

In [ ]:
titanic_data.isna().sum()

In [ ]:
titanic_data.isna().mean()*100

In [ ]:
titanic_data.drop(['deck'], axis = 1, inplace=True)

In [ ]:
median = titanic_data.age.median()
print(median)

In [ ]:
mean = np.round(titanic_data.age.mean(),0)
print(mean)

In [ ]:
titanic_data['Median_Age'] = titanic_data['age'].fillna(median)

In [ ]:
titanic_data['Mean_Age'] = titanic_data.age.fillna(mean)

In [ ]:
titanic_data

In [ ]:
titanic_data.isna().sum()

Veamos cómo queda la distribución con cada una de las imputaciones respecto de la distribución original

In [ ]:
titanic_data.describe()

In [ ]:
fig = plt.figure()
ax = fig.add_subplot(111)

titanic_data['age'].plot(kind='kde', ax=ax)

titanic_data['Median_Age'].plot(kind='kde', ax=ax, color='red')

titanic_data['Mean_Age'] .plot(kind='kde', ax=ax, color='green')

lines, labels = ax.get_legend_handles_labels()
ax.legend(lines, labels, loc='best')

In [ ]:
titanic_data["age"].describe()

In [ ]:
titanic_data["Mean_Age"].describe()

In [ ]:
titanic_data["Median_Age"].describe()

- Se recomienda usar cuando la data faltante es al azar
- Si la data tiene un distribución simétrica, se recomienda imputar por la media. En caso contrario, por la mediana.

#### Imputación por valor arbitrario

- Se escoge un valor cualquiera para reemplazar los missing values
- El valor NO debe pertenecer al dataset

Veamos ahora un ejemplo utilizando el dataset Titanic

In [ ]:
titanic_data_sub  = titanic_data[["survived", "pclass", "age", "fare"]]

In [ ]:
titanic_data_sub['age_99'] = titanic_data_sub.age.fillna(99)
titanic_data_sub['age_minus10'] = titanic_data_sub.age.fillna(-100)
titanic_data_sub

In [ ]:
fig = plt.figure()
ax = fig.add_subplot(111)

titanic_data_sub['age'].plot(kind='kde', ax=ax)

titanic_data_sub['age_99'].plot(kind='kde', ax=ax, color='red')

titanic_data_sub['age_minus10'].plot(kind='kde', ax=ax, color='green')

lines, labels = ax.get_legend_handles_labels()
ax.legend(lines, labels, loc='best')

#### Imputación por categoría "missing"

Esto es la versión de imputación arbitraria pero llevada al caso de variables categóricas

In [ ]:
titanic_data_sub  = titanic_data[["embark_town", "age", "fare"]]

In [ ]:
titanic_data_sub.isna().sum()

In [ ]:
titanic_data_sub.embark_town.fillna('missing', inplace=True)

In [ ]:
sns.countplot(x="embark_town", data=titanic_data_sub)

In [ ]:
titanic_data_sub["embark_town"].value_counts()

# Estadísticas Descriptivas

Las estadísticas descriptivas nos ayudan a tener nociones de como se están comportando nuestros datos y que podemos esperar de ellos en relación a sus valores. En este sentido, las estadísticas básicas que se utilizan son:

- Medidas de tendencia central: Media, Mediana, Moda
- Medidas de dispersión: Rango, Varianza, Desviación estándar
- Medidas de forma: Skewness y Kurtosis

A continuación, revisaremos como podemos obtener cada una de estas medidas utilizando el dataset salud

In [ ]:
salud.head()

In [ ]:
#A Nivel general
salud.describe()

In [ ]:
#A nivel más detallado
est_descr = salud.groupby(['SEXO','N_EDU'])[['SODIO_ORINA','GLUCOSA']].agg([np.mean,np.median,min,max])
est_descr

In [ ]:
salud.info()

In [ ]:
#Para una variable
print(salud.EDAD.mean())
print(salud.EDAD.median())
print(salud.EDAD.std())
print(salud.EDAD.skew())
print(salud.EDAD.kurtosis())